
Course.create(:title => 'CS101 - BUILDING A SEARCH ENGINE', :url => 'http://www.udacity.com/overview/Course/cs101', :offered_by => 'Udacity', :main_topic => 'Python', :description => 'This class will give you an introduction to computing. In seven weeks, you will build your own search engine complete with a web crawler and way of ranking popular pages. You will understand some of the key concepts in computer science, and learn how to write your own computer programs. No previous background in programming is expected.', :user_id => 1)

Course.create(:title => 'CS212 - DESIGN OF COMPUTER PROGRAMS', :url => 'http://www.udacity.com/overview/Course/cs212', :offered_by => 'Udacity', :main_topic => 'Intermediate Programming', :description => 'The key to progressing from a novice programmer to an expert is mindful practice. In this class you will practice going from a problem description to a solution, using a series of assignments. With each problem you will learn new concepts, patterns, and methods that will expand your ability and help move you along the path from novice towards expertise.', :user_id => 1)

Course.create(:title => 'CS253 - WEB APPLICATION ENGINEERING', :url => 'http://www.udacity.com/overview/Course/cs253', :offered_by => 'Udacity', :main_topic => 'Web Applications', :description => 'Web applications have the power to provide useful services to millions of people worldwide. In this class, you will learn how to build your own blog application starting from the basics of how the web works and how to set up a web application and process user input, to how to use databases, manage user accounts, interact with other web services, and make your application scale to support large numbers of users.', :user_id => 1)

Course.create(:title => 'CS262 - PROGRAMMING LANGUAGES', :url => 'http://www.udacity.com/overview/Course/cs262', :offered_by => 'Udacity', :main_topic => 'JavaScript', :description => 'This class will give you an introduction to fundamentals of programming languages. In seven weeks, you will build your own simple web browser complete with the ability to parse and understand HTML and JavaScript. You will learn key concepts such as how to specify and process valid strings, sentences and program structures. Then, you will design and build an interpreter - a program that simulates other programs.', :user_id => 1)

Course.create(:title => 'CS373 - PROGRAMMING A ROBOTIC CAR', :url => 'http://www.udacity.com/overview/Course/cs373', :offered_by => 'Udacity', :main_topic => 'AI', :description => 'This class, taught by one of the foremost experts in AI, will teach you basic methods in Artificial Intelligence, including: probabilistic inference, computer vision, machine learning, and planning, all with a focus on robotics. Extensive programming examples and assignments will apply these methods in the context of building self-driving cars. You will get a chance to visit, via video, the leading research labs in the field, and meet the scientists and engineers who are building self-driving cars at Stanford and Google. Prerequisites: The instructor will assume solid knowledge of programming, all programming will be in Python. Knowledge of probability and linear algebra will be helpful.', :user_id => 1)

Course.create(:title => 'CS387 - APPLIED CRYPTOGRAPHY', :url => 'http://www.udacity.com/overview/Course/cs387', :offered_by => 'Udacity', :main_topic => 'Cryptography', :description => "Description: Cryptography is about 'secret writing'. In this class, we will introduce the mathematical foundations of cryptography and build programs to perform encryption. We will see how to use cryptography to solve important problem such as how to authenticate users, secure websites, and do computation without exposing up your data. We will also look at the things that can go wrong when cryptography is misused or implemented badly.", :user_id => 1)

Course.create(:title => 'Model Thinking', :url => 'https://www.coursera.org/modelthinking/auth/welcome', :offered_by => 'Coursera', :main_topic => 'Data Models', :description => "Models help us to better organize information - to make sense of that fire hose or hairball of data (choose your metaphor) available on the Internet. Models improve our abilities to make accurate forecasts. They help us make better decisions and adopt more effective strategies. They even can improve our ability to design institutions and procedure. In this class, I present a starter kit of models: I start with models of tipping points. I move on to cover models explain the wisdom of crowds, models that show why some countries are rich and some are poor, and models that help unpack the strategic decisions of firm and politicians. For each model, I present a short, easily digestible overview lecture. Then, I'll dig deeper. I'll go into the technical details of the model. Those technical lectures won't require calculus but be prepared for some algebra. For all the lectures, I'll offer some questions and we'll have quizzes and even a final exam. If you decide to do the deep dive, and take all the quizzes and the exam, you'll receive a certificate of completion. If you just decide to follow along for the introductory lectures to gain some exposure that's fine too. It's all free. And it's all here to help make you a better thinker!", :user_id => 1)

Course.create(:title => 'Software as a Service', :url => 'https://www.coursera.org/saas/class', :offered_by => 'Coursera', :main_topic => 'SAAS', :description => "This course teaches the engineering fundamentals for long-lived software using the highly-productive Agile development method for Software as a Service (SaaS) using Ruby on Rails. Agile developers continuously refine and refactor a working but incomplete prototype until the customer is happy with result, with the customer offering continuous feedback. Agile emphasizes user stories to validate customer requirements; test-driven development to reduce mistakes; biweekly iterations of new software releases; and velocity to measure progress. We will introduce all these elements of the Agile development cycle, and go through one iteration by adding features to a simple app and deploying it on the cloud using tools like Github, Cucumber, RSpec, SimpleCov, Pivotal Tracker, and Heroku.", :user_id => 1)

Course.create(:title => 'Computer Vision', :url => 'http://www.vision-class.org/', :offered_by => 'Coursera', :main_topic => 'Algorithms', :description => "Computer vision seeks to develop algorithms that replicate one of the most amazing capabilities of the human brain - inferring properties of the external world purely by means of the light reflected from various objects to the eyes. We can determine how far away these objects are, how they are oriented with respect to us, and in relationship to various other objects. We reliably guess their colors and textures, and we can recognize them - this is a chair, this is my dog Fido, this is a picture of Bill Clinton smiling. We can segment out regions of space corresponding to particular objects and track them over time, such as a basketball player weaving through the court.", :user_id => 1)

Course.create(:title => 'Natural Language Processing', :url => 'https://www.coursera.org/nlp/auth/welcome', :offered_by => 'Coursera', :main_topic => 'Language Processing', :description => "The course covers a broad range of topics in natural language processing, including word and sentence tokenization, text classification and sentiment analysis, spelling correction, information extraction, parsing, meaning extraction, and question answering, We will also introduce the underlying theory from probability, statistics, and machine learning that are crucial for the field, and cover fundamental algorithms like n-gram language modeling, naive bayes and maxent classifiers, sequence models like Hidden Markov Models, probabilistic dependency and constituent parsing, and vector-space models of meaning.", :user_id => 1)

Course.create(:title => 'Game Theory', :url => 'https://www.coursera.org/gametheory/auth/welcome', :offered_by => 'Coursera', :main_topic => 'Game Theory', :description => "Popularized by movies such as 'A Beautiful Mind', game theory is the mathematical modeling of strategic interaction among rational (and irrational) agents. Beyond what we call 'games' in common language, such as chess, poker, soccer, etc., it includes the modeling of conflict among nations, political campaigns, competition among firms, and trading behavior in markets such as the NYSE. How could you begin to model eBay, Google keyword auctions, and peer to peer file-sharing networks, without accounting for the incentives of the people using them? The course will provide the basics: representing games and strategies, the extensive form (which computer scientists call game trees), Bayesian games (modeling things like auctions), repeated and stochastic games, and more. We'll include a variety of examples including classic games and a few applications.", :user_id => 1)

Course.create(:title => 'Probabilistic Graphical Models', :url => 'https://www.coursera.org/pgm/auth/welcome', :offered_by => 'Coursera', :main_topic => 'PGM', :description => "In this class, you will learn the basics of the PGM representation and how to construct them, using both human knowledge and machine learning techniques; you will also learn algorithms for using a PGM to reach conclusions about the world from limited and noisy evidence, and for making good decisions under uncertainty. The class covers both the theoretical underpinnings of the PGM framework and practical skills needed to apply these techniques to new problems. ", :user_id => 1)

Course.create(:title => 'Cryptography', :url => 'https://www.coursera.org/crypto/auth/welcome', :offered_by => 'Coursera', :main_topic => 'Cryptography', :description => "Cryptography is an indispensable tool for protecting information in computer systems. This course explains the inner workings of cryptographic primitives and how to correctly use them. Students will learn how to reason about the security of cryptographic constructions and how to apply this knowledge to real-world applications. The course begins with a detailed discussion of how two parties who have a shared secret key can communicate securely when a powerful adversary eavesdrops and tampers with traffic. We will examine many deployed protocols and analyze mistakes in existing systems. The second half of the course discusses public-key techniques that let two or more parties generate a shared secret key. We will cover the relevant number theory and discuss public-key encryption, digital signatures, and authentication protocols. Towards the end of the course we will cover more advanced topics such as zero-knowledge, distributed protocols such as secure auctions, and a number of privacy mechanisms. Throughout the course students will be exposed to many exciting open problems in the field.", :user_id => 1)

Course.create(:title => 'Design and Analysis of Algorithms', :url => 'https://www.coursera.org/algo/auth/welcome', :offered_by => 'Coursera', :main_topic => 'Algorithms', :description => "In this course you will learn several fundamental principles of algorithm design. You'll learn the divide-and-conquer design paradigm, with applications to fast sorting, searching, and multiplication. You'll learn several blazingly fast primitives for computing on graphs, such as how to compute connectivity information and shortest paths. Finally, we'll study how allowing the computer to 'flip coins' can lead to elegant and practical algorithms and data structures. Learn the answers to questions such as: How do data structures like heaps, hash tables, bloom filters, and balanced search trees actually work, anyway? How come QuickSort runs so fast? What can graph algorithms tell us about the structure of the Web and social networks? Did my 3rd-grade teacher explain only a suboptimal algorithm for multiplying two numbers?", :user_id => 1)

Course.create(:title => 'Introduction to Computer Science and Programming', :url => 'http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/', :offered_by => 'MIT', :main_topic => 'Python', :description => "This subject is aimed at students with little or no programming experience. It aims to provide students with an understanding of the role computation can play in solving problems. It also aims to help students, regardless of their major, to feel justifiably confident of their ability to write small programs that allow them to accomplish useful goals. The class will use the Python programming language.", :user_id => 1)


#Course.create(:title => '', :url => '', :offered_by => '', :main_topic => '', :description => "", :user_id => 1)
